Slight change to the save file
TypeError: write() argument must be str, not bytes
output file needs to be opened in binary mode
'w' needs to be changed to 'wb'